sulu/SuluFormBundle

CHANGELOG.md
Entity/Dynamic.php

`$HIDDEN_TYPES` is used in `Sulu\Bundle\FormBundle\ListBuilder\DynamicListFactory`

Fixed dynamic list factory with hidden fields

---

CHANGELOG.md
Mail/Helper.php
Mail/HelperInterface.php
Mail/NullHelper.php
UPGRADE.md

Without configuration (in the installation process) the `cache:clear` fails with the exception:
```
PHP Fatal error:  Class Sulu\Bundle\FormBundle\Mail\NullHelper contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Sulu\Bundle\FormBundle\Mail\HelperInterface::getReceiverTypes) in /app/vendor/sulu/sulu-form-bundle/Mail/NullHelper.php on line 17
```
see the slack channel https://sulu-io.slack.com/archives/C0430GGCV/p1506653176000156

Removed unused function "getReceiverTypes"

---

Configuration/FormConfigurationFactory.php

If only the email was set, the function always returned "null".

Remove null value

---

CHANGELOG.md
TitleProvider/StructureTitleProvider.php

Fix a problem when a page with a form is loaded over `sulu_content_load` and no `structure` is available on this route.

Avoid error when structure is not found

---

CHANGELOG.md
ListBuilder/DynamicListFactory.php

| Q | A
| --- | ---
Remove array_merge from list factory and replace it with a simple array push.
It improve the performance for big results x10.

Fix csv export for big results

---

.gitignore
CHANGELOG.md
DependencyInjection/CompilerPass/RemoveTaggedServiceCollectorCompilerPass.php
DependencyInjection/Configuration.php
DependencyInjection/SuluFormExtension.php
Resources/doc/dynamic.md
SuluFormBundle.php

| Q | A
| --- | ---
Allow to remove field type by a config definition
There is a lot of field setted and we don't always need all of them.
This provide a control on which field a user can use.
```config.yml
sulu_form:
dynamic_disabled_types:
- firstName
- lastName
- street
- zip 
- city
- state 
- function
- company
- phone
- fax
- country
- attachment
- salutation
- title
```

Allow to remove field type by a config definition

---

.styleci.yml
CHANGELOG.md
Controller/FormController.php

| Q | A
| --- | ---
Add created date field descriptor.
To show the user when a form was created.

Add created date to list view

---

CHANGELOG.md
Form/Builder.php

| Q | A
| --- | ---
Disable csrf token when recaptcha field exist.
Active reacaptcha make the csrf token irrelevant.
1. Create a form with recaptcha and a form without recaptcha.

Disable csrf token when recaptcha is active

---

CHANGELOG.md
DependencyInjection/Configuration.php

| Q | A
| --- | ---
Avoid normalize keys in dynamic widths configuration.
That the key of dynamic widths and ajax templates allow to use dashes.
```php
sulu_form:
dynamic_widths:
full: sulu_form.width.full
half: sulu_form.width.half
one-third: sulu_form.width.one-third
two-thirds: sulu_form.width.two-thirds
one-quarter: sulu_form.width.one-quarter
three-quarters: sulu_form.width.one-sixth
five-sixths: sulu_form.width.five-sixths
```

Avoid normalize keys for dynamic widths and ajax templates configuration

---

CHANGELOG.md
Resources/translations/sulu/backend.de.xlf
Resources/translations/sulu/backend.en.xlf
Resources/views/forms/template.html.twig

| Q | A
| --- | ---
Move submit label to form fields configuration and cleanup html structure of form template.
Submit label has more todo with the form as with the website. 
There was an unclosed tag in the first block.

Fix form template structure and move submit label

---

CHANGELOG.md
Twig/FormTwigExtension.php

| Q | A
| --- | ---
| Fixed tickets | fixes no
| Related issues/PRs | no
Write the form returned by the formBuilder in a simple variable instead of a php list().
Added early return to prevent a error if the selected form got deleted.
Fixes a bug inside of the FormTwigExtension which results in a symfony error if you try to get a form by id (sulu_form_get_by_id).
Use the twig extension as before.

Fix sulu_form_get_by_id twig extension

---

.travis.yml
composer.json

| Q | A
| --- | ---
Use branch alias for 2.0 development
To allow install sulu form bundle as 2.0@dev requirement.
```bash
composer require sulu/sulu-form-bundle:^2.0@dev
```

Use branch alias for 2.0 development

---

CHANGELOG.md
DependencyInjection/Configuration.php
DependencyInjection/SuluFormExtension.php
Event/MailchimpListSubscriber.php
Resources/config/type_mailchimp.xml
Resources/doc/mailchimp.md

| Q | A
| --- | ---
Added new configuration to change the subsribe status of mailchimp.
To add the possibility to change the default (`subsribed`) to (`pending`), which is needed in some projects.
```config.yml
sulu_form:
mailchimp_subscribe_status: "%parameter_recommended_for_mailchimp_subscribe_status%"
```
None

Added possibility to change mailchimp subscribe status

---

CHANGELOG.md
Configuration/FormConfigurationFactory.php

| Q | A
| --- | ---
Added formData parameter to getNotifySubject function in FormConfigurationFactory.
Because we want to get content from the formData in the getNotifySubject function.

Added formdata parameter to getNotifySubject function in FormConfigurationFactory

---

CHANGELOG.md
Resources/config/services.xml

| Q | A
| --- | ---
| Fixed tickets | fixes #168
Add missing navigation provider service for static templates.
Service did get lost a long time ago 🤔

Fixed missing `sulu_form.navigation_provider.template` service

---

CHANGELOG.md
Resources/doc/static.md

| Q | A
| --- | ---
As title suggests. There has been bad Grammar in the documentation.
Documentation Grammar.

Fixed Grammar in Documentation of static forms

---

CHANGELOG.md
Dynamic/Types/MailchimpType.php

| Q | A
| --- | ---
| Fixed tickets | fixes #176
Increase mailchimp limit from 10 to 100.
Sometimes there are more than 10 lists in mailchimp.
Describe BC breaks/deprecations here. (remove this section if not needed)

Increase mailchimp limit from 10 to 100

---

.travis.yml
CHANGELOG.md

| Q | A
| --- | ---
Start the mysql service manually.
Service not longer started automatically: See https://docs.travis-ci.com/user/reference/xenial/#services-disabled-by-default

Fix travis mysql service

---

.travis.yml

| Q | A
| --- | ---
Fix travis ci for php 5.5.
Travis seems not support php 5.5 on there new dist. See https://travis-ci.org/sulu/SuluFormBundle/jobs/564920930

Fix travis ci build for php 5.5

---

Controller/FormController.php
Manager/FormManager.php
Resources/config/form-fields/default_field_extended.xml
Resources/config/form-fields/field_attachment.xml
Resources/config/form-fields/field_choices.xml
Resources/config/form-fields/field_date.xml
Resources/config/form-fields/field_mailchimp.xml
Tests/Functional/Controller/FormControllerTest.php

| Q | A
| --- | ---
| Fixed tickets | 
| Related issues/PRs | https://github.com/sulu/sulu/pull/4636
This PR uses nested json properties in the xml files for the form field blocks. In order to work the PR https://github.com/sulu/sulu/pull/4636 has to be merged previously into the Sulu Core.
Instead of 
```xml
<property name="options[choices]" type="text_area"/>
```
the nested properties are accessed in the following way
```xml
<property name="options/choices" type="text_area"/>
```
This allows to simplify the logic of retrieving and storing of options in the FormController and FormManager.

Use nested json properties in form field blocks

---

DependencyInjection/SuluFormExtension.php
Dynamic/FormFieldTypeConfiguration.php
Dynamic/Helper/MailchimpListSelect.php
Dynamic/Types/AttachmentType.php
Dynamic/Types/CheckboxMultipleType.php
Dynamic/Types/CheckboxType.php
Dynamic/Types/DateType.php
Dynamic/Types/DropdownMultiple.php
Dynamic/Types/DropdownType.php
Dynamic/Types/FreeTextType.php
Dynamic/Types/HeadlineType.php
Dynamic/Types/MailchimpType.php
Dynamic/Types/RadioButtonsType.php
Dynamic/Types/RecaptchaType.php
Dynamic/Types/SpacerType.php
Dynamic/Types/TextType.php
Dynamic/Types/TextareaType.php
Resources/config/form-fields/field_mailchimp.xml
Resources/config/type_mailchimp.xml
Resources/doc/mailchimp.md

| Q | A
| --- | ---
| Fixed tickets | 
| Related issues/PRs | 
This PR adds a `MailchimpListSelect` helper class which is used in the `field_mailchimp.xml` to load the mailchimp lists and display them in a single select field. The mailchimp lists are loaded in the helper class in the same way as previously in the `MailchimpType` class.
Furthermore the property `attributes` is removed in the `FormFieldTypeConfiguration` because it is not used anymore by any dynamic type.
The changes in this PR are not properly tested yet.
The `field_mailchimp.xml` needs to load the mailchimp lists dynamically for a given account defined by the API key.
Describe BC breaks/deprecations here. (remove this section if not …

Mailchimp List Select 

---

Admin/DynamicListAdmin.php

| Q | A
| --- | ---
| Fixed tickets | none
| Related issues/PRs | requires sulu/sulu#5002
This PR ensures that the `DynamicListAdmin` is called at the end of the admin chain.

Add priority and check for existing view

---

DependencyInjection/Configuration.php
DependencyInjection/SuluFormExtension.php
Mail/Helper.php
Resources/config/services.xml
Resources/doc/index.md

| Q | A
| --- | ---
| Fixed tickets | fixes #194 
Add extra "sender" configuration parameter to add a Sender-header to the mail envelope.

#194 Add sender the same as parameter for Sender-header on envelope

---

Resources/config/lists/forms.xml

| Q | A
| --- | ---
| Fixed tickets | fixes #228 
| Related issues/PRs | #228 
Removes filter type attribute
To make the bundle compatible with sulu 2.1.*@dev

Remove filter type attributes from form list definition

---

Metadata/DynamicFormMetadataLoader.php
Tests/Functional/Metadata/DynamicFormMetadataLoaderTest.php

| Q | A
| --- | ---
| Fixed tickets | fixes #226
| Related issues/PRs | #226
Sorts form field types alphabetically by title.
The form field types were not sorted alphabetically before.

Add locale specific sorting of form field types

---

Entity/FormFieldTranslation.php

| Q | A
| --- | ---
Fixes the type hints for the `$title` of the `FormFieldTranslation.php` as it is nullable.
Because it's not possible to save a form with a field that doesn't have a title, e.g. the `spacer`.
Currently following error is displayed:
```
message: "Argument 1 passed to Sulu\Bundle\FormBundle\Entity\FormFieldTranslation::setTitle() must be of the type string, null given, called in /Users/thomas.duenser/Development/websites/zuend.lo/vendor/sulu/sulu-form-bundle/Manager/FormManager.php on line 215"
```

Fixed nullable form field translation

---

Resources/doc/index.md
composer.json

| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluFormBundle/issues/223
Renames the package name to `sulu\form-bundle`.
Because we want consistency between all sulu-bundles.

Rename package to sulu/form-bundle

---

Entity/Dynamic.php
Metadata/DynamicFormMetadataLoader.php
Resources/config/doctrine/Dynamic.orm.xml
UPGRADE.md

| Q | A
| --- | ---
Adjusts the database columns to have a consistent data set.
The database table is much more readable with less columns and some columns had keywords for MySql 8 as their name.

Reduce dynamic entity to basic fields

---

CHANGELOG.md
Resources/views/mails/notify.html.twig

| Q | A
| --- | ---
| Fixed tickets | fixes #214
Fix line breaks in notify emails.
Line breaks should appear in the value

Fix line breaks in notify emails

---

.travis.yml
Configuration/FormConfigurationFactory.php
DependencyInjection/Configuration.php
DependencyInjection/SuluFormExtension.php
Form/Handler.php
Form/HandlerInterface.php
Form/Type/DynamicFormType.php
Resources/config/services.xml
Resources/doc/dynamic.md

| Q | A
| --- | ---
| Fixed tickets | fixes #212
Add possibility for a honeypot field
To avoid spams
```yaml
sulu_form:
dynamic_honeypot_field: "Honey Pot Field Name"
dynamic_honeypot_strategy: spam # no_save, no_email, spam
```

Add possibility for a honeypot field

---

Entity/FormFieldTranslation.php

| Q | A
| --- | ---
Remove paragraphs from labels
Currently ckeditor will always wrap around labels this can be removed when https://github.com/sulu/sulu/issues/5214 is fixed.

Remove paragraphs from labels

---

Controller/FormController.php

| Q | A
| --- | ---
| Related issue | #245 
A fix for the sorting issue on save
When you save the form after you sorted some fields, the fields get reset to it's original position until page reload.

Fix field order after save

---

ListBuilder/DynamicListBuilder.php

| Q | A
| --- | ---
| Fixed tickets | fixes #249 
Allow string|array in getMediaUrls.
Fix dynamic list builder media urls.

Fix dynamic list builder media urls

---

Entity/Dynamic.php
Entity/Form.php
Form/Type/DynamicFormType.php
UPGRADE.md

| Q | A
| --- | ---
| BC breaks? | yes
| Fixed tickets | part of #190  
Avoid magic setter and getter in dynamic form.
Magic setter and getter should always be avoided.

Avoid magic setter and getter in dynamic form

---

Resources/config/forms/form_details.xml

| Q | A
| --- | ---
| Fixed tickets | fixes #256 
Make from and to email in form details not required, because they fallback to configured from and to emails.
If no email addresses are configured and no email addresses are entered in the form details, form submit works, but no email is being sent.

Make from and to email not required
