- CHANGELOG.md
- Resources/doc/csrf.md
- Resources/doc/dynamic.md
- Resources/doc/theming.md
- Resources/views/themes/dynamic.html.twig
> Added basic theme for dynamic forms

- CHANGELOG.md
- Entity/Dynamic.php
- UPGRADE.md
> Added blameable interface to dynamic entity

- CHANGELOG.md
- Resources/translations/sulu/backend.de.xlf
- Resources/translations/sulu/backend.en.xlf
- Resources/translations/sulu/backend.fr.xlf
- Resources/views/forms/fields/default-field.html.twig
> Rename placeholder field to example

- CHANGELOG.md
- Resources/translations/messages.nl.xliff
- Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
Added the Dutch translations.
> Added Dutch translations

- .gitattributes
- CHANGELOG.md
- Controller/FormController.php
- Entity/FormTranslation.php
- Manager/FormManager.php
- Tests/Functional/Controller/FormControllerTest.php
- Tests/app/AppKernel.php
- Tests/app/config/config_admin_dev.yml
- Tests/app/config/config_admin_test.yml
- Tests/app/config/config_website.yml
- Tests/app/config/config_website_dev.yml
- Tests/app/config/config_website_prod.yml
- Tests/app/config/config_website_test.yml
- Tests/app/config/routing_admin.yml
- Tests/app/config/routing_website.yml
- UPGRADE.md
- composer.json
Add tests to the form controller and fix not found error which currently did throw a 500 errors.
> Fix formcontroller 404 handling and add tests

- CHANGELOG.md
- Controller/TemplateController.php
- Dynamic/FormFieldTypeConfiguration.php
- Dynamic/Types/AttachmentType.php
- Dynamic/Types/CheckboxMultipleType.php
- Dynamic/Types/CheckboxType.php
- Dynamic/Types/DateType.php
- Dynamic/Types/DropdownMultiple.php
- Dynamic/Types/DropdownType.php
- Dynamic/Types/FreeTextType.php
- Dynamic/Types/HeadlineType.php
- Dynamic/Types/MailchimpType.php
- Dynamic/Types/RadioButtonsType.php
- Dynamic/Types/RecaptchaType.php
- Dynamic/Types/SpacerType.php
- Dynamic/Types/TextType.php
- Dynamic/Types/TextareaType.php
- Form/Builder.php
- Resources/views/forms/template.html.twig
- UPGRADE.md
> Add grouped types to admin block

- CHANGELOG.md
- Controller/TemplateController.php
- DependencyInjection/Configuration.php
- DependencyInjection/SuluFormExtension.php
> Add widths to bundle configuration

- CHANGELOG.md
- Resources/config/services.xml
> Fixed unknown parameter secret exception

- .travis.yml
- Admin/DynamicListNavigationProvider.php
- CHANGELOG.md
- Configuration/FormConfiguration.php
- Configuration/FormConfigurationFactory.php
- Configuration/MailConfigurationInterface.php
- Dynamic/Checksum.php
- Entity/Form.php
- Form/Type/DynamicFormType.php
- Mail/Helper.php
- Manager/FormManager.php
- Resources/doc/recaptcha.md
- Tests/Unit/Configuration/FormConfigurationFactoryTest.php
- composer.json
- phpstan.neon
added phpstan on level 2.
created an issue to fix the problems with the other levels: #117
> Add phpstan static code analyzer on level 2

- .gitignore
- Resources/translations/sulu/backend.fr.xlf
| Q | A
| --- | ---
update french translations
for a better french understanding
> update french translations

- CHANGELOG.md
- ListBuilder/DynamicListFactory.php
| Q | A
| --- | ---
| Fixed tickets | fixes #123
Remove type from date field descriptor to fix list view.
Currently the frontend can't convert the date into a correct value and return nothing.
> Fix date field in list view

- .gitignore
- Form/Handler.php
| Q | A
| --- | ---
fix bug about sending attachments in information mail
attachments in mail information are not sending when form is submit
> Fix sending bug attachments

- CHANGELOG.md
- Configuration/FormConfigurationFactory.php
- Form/Handler.php
- Resources/views/mails/notify.html.twig
| Q | A
| --- | ---
Add the correct serialized form to the email template.
Currently the medias are not available in the email template.
> Fix handle files in email template

- CHANGELOG.md
- Configuration/FormConfigurationFactory.php
- Form/Handler.php
- ListBuilder/DynamicListFactory.php
- Resources/views/mails/notify.html.twig
| Q | A
| --- | ---
Release candiate for 1.0.0-RC1
Its time for going stable.
> Release 1.0.0-RC1

- CHANGELOG.md
- UPGRADE.md
| Q | A
| --- | ---
Improve upgrade guide for 0.2.0
The doctrine:schema:update can end in strange errors and content lose so this should not be recommended in any way.
> Improve upgrade guide for 0.2.0

- CHANGELOG.md
- Resources/doc/dropzone.md
| Q | A
| --- | ---
Fix implement dropzone documentation
False function name.
> Fix implement dropzone documentation

- CHANGELOG.md
- Configuration/FormConfigurationFactory.php
- Controller/FormWebsiteController.php
- Resources/doc/static.md
| Q | A
| --- | ---
Fix static form handling after refractoring.
Static forms did not longer work.
> Fix static form handling after refractoring

- CHANGELOG.md
- DependencyInjection/Configuration.php
- DependencyInjection/SuluFormExtension.php
- Event/MailchimpListSubscriber.php
- Resources/config/type_mailchimp.xml
- Resources/doc/mailchimp.md
| Q | A
| --- | ---
Add mailchimp subscribe status feature to master branch.
Is a 1.x feature.
> Add mailchimp subscribe status feature to master branch

- CHANGELOG.md
- Content/Types/FormSelect.php
- Entity/Dynamic.php
- Event/RequestListener.php
- Form/Builder.php
- Form/Handler.php
- Form/Type/DynamicFormType.php
| Q | A
| --- | ---
| Fixed tickets | fixes #174
Fixed form on a  shadow page.
Currently if a form is embedded on the same locale and submitted
1. Create a Form only in EN
2. Create a Page in EN and select the form
3. Create DE Page as Shadow on EN
4. Submit the form
> Fixed form on a shadow page

- .travis.yml
- CHANGELOG.md
- README.md
- UPGRADE.md
- composer.json
| Q | A
| --- | ---
Add compatibility to php 7.3.
Newer is always better they said 😆 .
> Add php 7.3 to travis test runs

- Admin/FormAdmin.php
- composer.json
| Q | A
| --- | ---
Update toolbar actions for RC3 compatibility
> Fix toolbar actions for Sulu2 RC3 compatibility

- composer.json
| Q | A
| --- | ---
| Fixed tickets | -
A fix of an accidentally added item in composer.json
Makes composer.json valid
-
-
Describe BC breaks/deprecations here. (remove this section if not needed)
- 
-
> Fix accidentally added item in composer

- DependencyInjection/SuluFormExtension.php
- Resources/translations/admin.de.json
- Resources/translations/admin.en.json
| Q | A
| --- | ---
| Fixed tickets | fixes #/206
Changed content type to overlay, so more then 10 forms can be shown to select.
> Change form selection to overlay

- .github/workflows/crowdin-upload.yaml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/4952
This PR uploads the available translations to [crowdin](https://sulu.crowdin.com/sulusulu-form-bundle).
So that people can edit translations there.
> Add job to upload translations to crowdin

- .github/PULL_REQUEST_TEMPLATE.md
- Resources/doc/dynamic.md
- Resources/doc/index.md
- Resources/doc/mailchimp.md
- Resources/doc/recaptcha.md
- Resources/doc/theming.md
| Q | A
| --- | ---
Update docs using Symfony 4 structure.
Sulu 2.x using the new Symfony 4 folder structure so the docs should point to this files not the old symfony 3.
> Update docs using Symfony 4 structure

- Configuration/FormConfigurationFactory.php
- Content/Types/SingleFormSelection.php
- Controller/DynamicController.php
- Dynamic/Checksum.php
- Entity/Dynamic.php
- Entity/FormTranslation.php
- Event/CacheInvalidationListener.php
- Exception/FormNotFoundException.php
- ListBuilder/DynamicListBuilder.php
- ListBuilder/DynamicListFactory.php
- Manager/FormManager.php
- Media/CollectionStrategyInterface.php
- Media/CollectionStrategySingle.php
- Media/CollectionStrategyTree.php
- Resources/config/services.xml
- Tests/Functional/Controller/FormControllerTest.php
- Tests/Functional/Metadata/DynamicListMetadataLoaderTest.php
- TitleProvider/StructureTitleProvider.php
- phpstan.neon
| Q | A
| --- | ---
Fix some type issues and increase phpstan to 5.
Some types where not correct formId is a int and not a string and fix some other phsptan issues and register the CacheInvalidator correctly..
> Fix CacheInvalidator and some type issues and increase phpstan to 5

- Admin/DynamicListAdmin.php
- Media/CollectionStrategyInterface.php
| Q | A
| --- | ---
This PR fixes the jexl condition for template data tabs.
> Fix tab condition for template

- Configuration/FormConfigurationFactory.php
- Configuration/MailConfiguration.php
- Configuration/MailConfigurationInterface.php
- Form/Handler.php
- Resources/config/routing.yml
- Resources/config/services.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #233 
| Related issues/PRs | #issuenum 
Fix rendering of static forms
To fix #233
> Fix rendering of static forms

- Form/Type/TypeInterface.php
- Manager/FormManager.php
- Metadata/DynamicFormMetadataLoader.php
- Repository/FormRepository.php
- Resources/config/services.xml
- Resources/doc/static.md
- Resources/views/themes/dynamic.html.twig
- composer.json
| Q | A
| --- | ---
Enhance controller referencing syntax
> Enhance controller referencing syntax

- Form/Handler.php
| Q | A
| --- | ---
Templating variable hasn't been replaced with the new one.
Which problem does the PR fix? (remove this section if you linked an issue above)
> Fix templating variable

- Resources/views/themes/dynamic.html.twig
| Q | A
| --- | ---
Fixes the reference to the FormWebsiteController.
The controller wasn't found anymore with the previous reference.
> Adjust FormWebsiteController reference in dynamic template

- .travis.yml
- Command/FormGeneratorCommand.php
- DependencyInjection/SuluFormExtension.php
- Entity/Form.php
- Entity/FormField.php
- Resources/config/doctrine/Form.orm.xml
- Resources/config/doctrine/FormField.orm.xml
- Resources/config/services.xml
- Resources/doc/dynamic.md
- Tests/Functional/Controller/FormControllerTest.php
- composer.json
| Q | A
| --- | ---
Add FormGeneratorCommand
Improve developer experience 
```bash
bin/console sulu:form:generate-form
```
> Add FormGeneratorCommand

- Command/FormGeneratorCommand.php
- Dynamic/Types/FreeTextType.php
- Dynamic/Types/HeadlineType.php
- Dynamic/Types/RadioButtonsType.php
- Dynamic/Types/SpacerType.php
- Entity/FormTranslation.php
- Resources/doc/csrf.md
- Resources/doc/dynamic.md
- Resources/doc/theming.md
- Resources/views/themes/basic.html.twig
- Resources/views/themes/dynamic.html.twig
| Q | A
| --- | ---
Add improved basic theme and fix some type errors. The new theme should make it a lot easier to customize it.
With:
- https://github.com/symfony/symfony/pull/30320
- https://github.com/symfony/symfony/pull/29862
we can improve the current theme and make it easier to customize it.
> Add improved basic theme

- Resources/doc/dynamic.md
- Resources/views/themes/basic.html.twig
| Q | A
| --- | ---
Improve honeypot doc.
The honeypot field need to be hidden in css.
> Improve honeypot doc

- Event/DynFormSavedEvent.php
- Event/FormSavePostEvent.php
- Event/FormSavePreEvent.php
- Event/MailchimpListSubscriber.php
- Form/Handler.php
- Form/HandlerInterface.php
- composer.json
| Q | A
| --- | ---
| Fixed tickets | part of #190
Update event dispatching.
To be compatibly with newest symfony version in future.
> Update event dispatching

- ListBuilder/DynamicListBuilder.php
| Q | A
| --- | ---
| Fixed tickets | fixes #249 
Use a number for the url generation.
Fix dynamic list with media
> Fix dynamic list with media

- Form/Handler.php
| Q | A
| --- | ---
| Related issues/PRs | #257
Fix the post save event
Accidentally a wrong event was inserted
> Fix PostSaveEvent

- Form/Handler.php
| Q | A
| --- | ---
Fix set of media in file upload.
We are not longer using magic setter since #255
> Fix set of media in file upload

- .travis.yml
- CHANGELOG.md
- Configuration/FormConfigurationFactory.php
- DependencyInjection/Configuration.php
- DependencyInjection/SuluFormExtension.php
- Form/Handler.php
- Form/HandlerInterface.php
- Form/Type/DynamicFormType.php
- Resources/config/services.xml
- Resources/doc/dynamic.md
| Q | A
| --- | ---
| New feature? | yes (copy from version for Sulu 2)
Also add the honeypot field possibility for this older version.
Spam problems.
In documentation
> Add possibility for a honeypot field for 1.x
